name: Data repository

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    name: Lint python files, repository.yaml, and folder structure
    runs-on: ubuntu-latest
    concurrency:
      # Cancel any previous runs with the same workflow name and branch
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    strategy:
      fail-fast: false
    env:
      HATCH_VERBOSE: 1
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          check-latest: true
      - name: Install hatch
        run: python -m pip install pipx && pipx install hatch
      - name: Lint Python files
        run: hatch run lintformat:lint
      - name: Lint repository.yaml and check mockup folder structure
        run: hatch run test:test
